# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('user', models.CharField(max_length=80, verbose_name='Who selected this god awful movie')),
                ('date', models.DateField(verbose_name='When was this movie played')),
            ],
        ),
    ]
