# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(verbose_name='TMDB ID'),
        ),
    ]
